### ISSUE TITLE
Fixed items with labels

### ISSUE THREAD

**Issue by dawidhyzy** [sephiroth74/Material-BottomNavigation#13]
How to set item label and icon to always shown?

**Comment by sephiroth74** [comment]
Fixed are those elements in a navigation bar with up to 3 item. Those always show icon and labels.

**Comment by dawidhyzy** [comment]
Is there an option to changed that? I really like your implementation but my project requirement  is with fixed elements.

**Comment by sephiroth74** [comment]
I'm sorry but the library follows the Google's guidelines for the bottombar implementation. 
https://material.google.com/components/bottom-navigation.html

**Comment by iNoles** [comment]
Then Reselect one should be removed over "Destinations requiring direct access"

**Comment by iNoles** [comment]
I haven't seen anything there about "Reselect"

**Comment by dawidhyzy** [comment]
Ok. It's insane that google does not respect its own rules - Google+ app for example.

**Comment by zayo** [comment]
Material design is only design guide created separately.
I think, that G+ app is not marked as Material design leader. Maybe it's not in Material at all yet. Please consider this before you hate :)

**Comment by wiliuzas** [comment]
Hello,
http://www.androidpolice.com/2016/11/11/google-play-newsstand-v4-0-begins-rolling-out-with-a-major-redesign-apk-download/
4 labels and icons always visible.

**Comment by sephiroth74** [comment]
well, in the material design guidelines I see this:

> If there are four or five actions, display inactive views as icons only

**Comment by leonardo2204** [comment]
@sephiroth74 Altough I agree with you, I think it would be cool to have an option to show the labels even if there are more then 3 tabs in your layout. Lots of major apps do this, like G+, Airbnb and so on !

**Comment by sephiroth74** [comment]
ok :)

**Comment by sephiroth74** [comment]
anyway, Google added the BottomNavigationView to support library. right now it's just a piece of garbage, but as soon as it will be stable this library will be deprecated.

**Comment by leonardo2204** [comment]
@sephiroth74 So, will it be implemented ?
And by the google lib, it really sucks, and I think it will for a long time, so I don't see your cool lib being deprecated in a near future :)

**Comment by sephiroth74** [comment]
Yes, I will implement it. Have to figure out where.

**Comment by leonardo2204** [comment]
Cool, thank you so much !
If you'd like, I can figure it out and drop a PR !

**Comment by sephiroth74** [comment]
you're more than welcome. I was thinking to add a field in the menu itself

**Comment by leonardo2204** [comment]
Hmm I was thinking the same... seems like a good idea!

**Comment by sephiroth74** [comment]
just pushed a new branch with this feature:
https://github.com/sephiroth74/Material-BottomNavigation/tree/feature/2.x

for gradle use: 2.0.0-rc02-SNAPSHOT
