### ISSUE TITLE
Conflict with Snackbar dismiss?

### ISSUE THREAD

**Issue by wakim** [sephiroth74/Material-BottomNavigation#16]
Hello,

When using the `BottomBehavior` and showing a Snackbar, it generates a bug on dismissal gesture of Snackbar. But using the TabletBehavior, this doesn't happen.

I'm using the sample app to reproduce the problem. Just click on FAB and try to dismiss the SnackBar.

I'll try to investigate, but i have no clue about this problem yet.

**Comment by sephiroth74** [comment]
Oh..  I didn't see this error before. When you say "try to dismiss the snackbar" what do you mean? Click on the snackbar action button?
Do you also have a stacktrace?

**Comment by wakim** [comment]
Hi @sephiroth74, i was using your library and detected this issue. And i was able to reproduce in your sample app too.

But the "try to dismiss the snackbar" is the horizontal dismiss based on the horizontal gesture, not the action. But does not generate any stacktrace.

Thanks in advanced.
