### ISSUE TITLE
Not work in any other layouts except CoordinatorLayout

### ISSUE THREAD

**Issue by WaylanPunch** [sephiroth74/Material-BottomNavigation#17]
**Material-BottomNavigation** can only work in the  **android.support.design.widget.CoordinatorLayout** ? Is it right?

**Comment by Hitexroid** [comment]
this is my question too !

**Comment by sephiroth74** [comment]
started working on it: https://github.com/sephiroth74/Material-BottomNavigation/tree/feature/no_coordinator

**Comment by WaylanPunch** [comment]
looking forward it

**Comment by sephiroth74** [comment]
it should be available now with the latest 2.0.1-rc1 release
