### ISSUE TITLE
Menu with 4 icons dispayed in black color

### ISSUE THREAD

**Issue by gerardopenya** [sephiroth74/Material-BottomNavigation#19]
Your component is a lifesaver for me.
I found the following behavior in my application.
I use it in two different (MainActivity) AppCompatActivity, only one is shown during the user session since it depends on the user profile.  I use a menu of three options in the first one and  one more option in the second,  four options total, all icons are white. 

But in the case of the second activity when this is displayed  icons appear in black.

I test the same layout deleting the fourth item from the menu and then the icons are displayed in white.
This behavior is only when the fourth menu option is present.

**Comment by zayo** [comment]
Hey, i got the same problem, but it was working with 4, but with three it wasn't.
<menu xmlns:android="http://schemas.android.com/apk/res/android"
      xmlns:app="http://schemas.android.com/apk/res-auto"
      app:bbn_rippleColor="@color/accent"
      app:bbn_itemColorInactive="@color/gray"
      app:bbn_itemColorActive="@color/white"
      android:background="@color/primary"
    >

defining all color attributes in menu helped me :)

**Comment by sephiroth74** [comment]
it should be fixed in the next version. The problem was that the menu used shared drawables.
