### ISSUE TITLE
Layout not scrolling, OnClickListeners not registering.

### ISSUE THREAD

**Issue by MiralDesai** [sephiroth74/Material-BottomNavigation#20]
Hi,

I just started using your library, and for the most part it works perfectly, however I have found a weird issue. On one `Fragment` I have a `RecyclerView` and it works perfectly, scrolls down the list, and the toolbar and bottom navigation both hide and reappear when scrolling.

I added another Fragment just now, and the layout is a simple `RelativeLayout`. When I move to that tab I do a .replace `FragmentTransaction` and it all works, however I cannot scroll in the layout, and all my `OnClickListeners` do not work. I can see the view has inflated, but I can't do anything with it.

Does this library only work with RecyclerViews/Listviews or something? Not quite sure what's going on.

Would appreciate any guidance on the matter. Thanks.

**Comment by iNoles** [comment]
you can add ScrollView or NestedScrollView to make RelativeLayout as a child of it.

**Comment by MiralDesai** [comment]
Hmm, I got the scrolling working by adding a margin to the bottom of my laptop to account for the Bottom Navigation, so I guess content can be hidden under there.

The weird thing is the BottomNavigation bar and Toolbar and not hiding when you scroll. Do you what the circumstances are for this to work? It works on my other tab with the RecyclerView.

**Comment by MiralDesai** [comment]
Using a ScrollView doesn't seem to work, however a NestedScrollView did work. Sorry didn't understand at first. Read this and realised ScrollViews don't work with CoordinatorLayouts 

https://inthecheesefactory.com/blog/android-design-support-library-codelab/en

**Comment by mugabi0978** [comment]
Kindly direct me on how you added onitemclick listeners to new fragments... i am looking for this feature but i dont seem to see it in the code. thanks
