### ISSUE TITLE
How to set the shadow of BottomNavigation

### ISSUE THREAD

**Issue by fg2q1q3q** [sephiroth74/Material-BottomNavigation#21]
![image](https://cloud.githubusercontent.com/assets/6970621/17768354/37cc23e8-6566-11e6-8b96-a29ac4edf23b.png)

As shown in the picture above, I expect the bottom menu and the content area to have a clear shadow.

**Comment by lopezzbelgium** [comment]
You can override this value in your project dimens.xml to clear the shadow:
 <dimen name="bbn_top_shadow_height">0dp</dimen>
