### ISSUE TITLE
Not working with support library 24.2.0

### ISSUE THREAD

**Issue by SEOJAEHWA** [sephiroth74/Material-BottomNavigation#22]
![screenshot_20160823-091015](https://cloud.githubusercontent.com/assets/4252435/17875982/8a247c72-6911-11e6-9354-737d0fcf170c.png)
As shown this picture, FAB goes up when 'snackbar' has been called.
It always happen on Project that added 'support library 24.2.0'.
Thanks.

**Comment by equatorapps** [comment]
Yup same here, works fine with 24.0.0.

**Comment by WonderCsabo** [comment]
Yep, i can also reproduce this.

**Comment by sephiroth74** [comment]
it should be fixed in the next release
