### ISSUE TITLE
[Q] How many items can I include in BottomNavigation?

### ISSUE THREAD

**Issue by am2222** [sephiroth74/Material-BottomNavigation#26]
Hi,
What is the maximum number of items which I can include in navigation?
Also Is it possible to add a numeric Badges to navigations?

**Comment by sdnuliu** [comment]
maximum number is five

**Comment by am2222** [comment]
@sdnuliu  thanks.and is there any way to add number badges into navigator?

**Comment by sephiroth74** [comment]
there's an example included in the sample app to do that.
