### ISSUE TITLE
Ability to avoid item getting selected?

### ISSUE THREAD

**Issue by MiralDesai** [sephiroth74/Material-BottomNavigation#31]
Is it possible to do this or add such a feature? I could do it manually if the previousPosition was exposed with a method like getPrevousSelectedPosition(); or similar.

**Comment by sephiroth74** [comment]
right now the only thing you can do is set android:enabled=false to the menu item you don't want to be clicked. 
But there's no public api to make it available at runtime. I'll add this in the next release

**Comment by MiralDesai** [comment]
Cool thanks. Not a big deal if I'm honest, because in all honesty it's not something that should be expected of the bottom bar. More just a nice to have.

**Comment by lopezzbelgium** [comment]
Would be cool if there is a preselect listener that still fires when a tab is selected (enabled or not). For a use case of mine one tab actually starts another app (sort of like facebook & messenger) so I don't really want the tab to get selected but still get notified when the item is tapped.
