### ISSUE TITLE
Disable default selected tab

### ISSUE THREAD

**Issue by QiiqeAzuara** [sephiroth74/Material-BottomNavigation#33]
Sometime selecting nothing is needed. 
using this way:
mBottomNav.setDefaultSelectedIndex(-1);  // Nothing tab is checked 👍 
but, when I select one :( NullPointerException, because is invalid position ...

`java.lang.NullPointerException: Attempt to invoke virtual method 'void it.sephiroth.android.library.bottomnavigation.BottomNavigationFixedItemView.setExpanded(boolean, int, boolean)' on a null object reference at it.sephiroth.android.library.bottomnavigation.FixedLayout.setSelectedIndex(FixedLayout.java:106)`

Is there a way to have a tab not selected when first time running?

**Comment by sephiroth74** [comment]
it's both a bug and a new feature. it shouldn't allow to select "nothing" now, but if you try it will crash (like you reported).
I'll add this feature in the next release.

**Comment by QiiqeAzuara** [comment]
@sephiroth cool ! Awesome library , Thanks

**Comment by sephiroth74** [comment]
you can review the changes here. now -1 can be used as selection. https://github.com/sephiroth74/Material-BottomNavigation/tree/feature/no_selection

**Comment by QiiqeAzuara** [comment]
@sephiroth74 Nice ! , Thanks

**Comment by sephiroth74** [comment]
it should be available now in maven too. version 2.0.1-rc1
