### ISSUE TITLE
Disable title for inactive items?

### ISSUE THREAD

**Issue by BinaryWaves** [sephiroth74/Material-BottomNavigation#34]
Your first shifting example displays the title active only when the menu item is selected, I can't find how to implement this feature from the library though?

Update: I might have found it? Need to test when I get to school.

Could you possibly post a list of the xml attributes available? They do not show up at all for me in Android Studio through autocompletes and was lucky I found one attribute in the source code  that isnt documented. Updated and expanded documentation would be greatly apprecieated, it is really limiting in terms of knowing what I can do with the ui xml and menu xml elements

**Comment by BinaryWaves** [comment]
Update: figured out it automatically hides titles if I make the number of nav items 5. It just doesn't work if you have 3?

**Comment by sephiroth74** [comment]
no it doesn't. by default with 3 items all the labels are visible.
anyway you can see the list of available attributes here:
https://github.com/sephiroth74/Material-BottomNavigation#styling
