### ISSUE TITLE
animation lag bug when specifying layout height.

### ISSUE THREAD

**Issue by BinaryWaves** [sephiroth74/Material-BottomNavigation#40]
Foreword edit: I just ran a test while writing this issue. Changing the height to wrap_content fixes the issue but I will still post to bring it to attention for others who need more direct height controls

Notice the bottom bar: http://imgur.com/i0bZMJZ

There is a horizontal line slightly above the translucent nav bar. In this picture I was in the green colored index and animated over to the blue colored index. The ripple doesn't expand throughout the entire bar evenly, it just goes across horizontally and the rest changes behind it a bit later. Even with a solid nav bar there is still a 4-5px line lagging behind on the bottom of the nav bar.

Using 2.0.1-rc1
Google Pixel, 7.1.1 if it matters

`<it.sephiroth.android.library.bottomnavigation.BottomNavigation
        android:id="@+id/view_main_nav"
        android:layout_width="match_parent"
        android:layout_height="56dp"
        android:layout_gravity="bottom"
        app:bbn_entries="@menu/nav_main"
        app:bbn_scrollEnabled="true"
        app:bbn_badgeProvider="@string/bbn_badgeProvider"
        app:layout_behavior="@string/bbn_default_view_behavior" />`

**Comment by sephiroth74** [comment]
you have to use either `wrap_content` or `match_parent`, not a specific dp size. the internal height of the navbar will be 56dp at the end, but the actual component will be bigger than that.
