### ISSUE TITLE
bbn_itemColorInactive seems not working

### ISSUE THREAD

**Issue by noiserr** [sephiroth74/Material-BottomNavigation#5]
Hi! Thanks for amazing library, but I have some issue. I've tried to change inactive item color but it appears to be not working!

Here's my menu.xml
`<menu xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:background="#e0e0e0"
    app:bbn_itemColorActive = "#3bb472"
    app:bbn_itemColorInactive = "#3b5fb4"
    app:bbn_rippleColor="#33ffffff">
    <item
        android:id="@+id/bbn_item1"
        android:icon="@drawable/ic_menu_manage"
        android:title="Cloud Sync" />
    <item
        android:id="@+id/bbn_item2"
        android:icon="@drawable/ic_menu_slideshow"
        android:title="Chromecast" />
    <item
        android:id="@+id/bbn_item3"
        android:icon="@drawable/ic_menu_slideshow"
        android:title="Mail" />
    <item
        android:id="@+id/action4"
        android:icon="@drawable/ic_menu_camera"
        android:title="List" />
</menu>`

And this is result:
https://s9.postimg.org/bpv9pe35r/Screen+Shot+2016-04-14+at+12.10.42.png

Please check it.

**Comment by sephiroth74** [comment]
It should be fixed right now. try the version `1.0.5-SNAPSHOT`.

Anyway, Google strongly recommend to avoid different colors for the bottombar navigation with shifting items:
http://www.google.com/design/spec/components/bottom-navigation.html#bottom-navigation-style

**Comment by noiserr** [comment]
Thanks, works like a charm!
