### ISSUE TITLE
custom badge doesn't work

### ISSUE THREAD

**Issue by tlzxsun** [sephiroth74/Material-BottomNavigation#8]
The CustomBadgeProvider works in your demo application, but doesn't work in my app. It's really weird. What' more weird is you libary cause color #ffffff turns into color_primary in my app, that's really annonying.

I just write a simple CustomBadgeProvider.java.
```
public class CustomBadgeProvider extends BadgeProvider{
    public CustomBadgeProvider(BottomNavigation navigation) {
        super(navigation);
    }


    Drawable getBadge(@IdRes int itemId) {
        return new BadgeDrawable(Color.BLUE, 192);
    }
}
```
but the badge doesn't change as i write in getBadge method.

**Comment by sephiroth74** [comment]
Have you also defined your `CustomBadgeProvider` in the layout xml?

**Comment by tlzxsun** [comment]
Yes, I have defined in layout xml and it works in some devices. But it doesn't work in nexus 5 6.0.1. I think   maybe it's the device problem or some thing.
