### ISSUE TITLE
how to add more then five item on bottom navigation

### ISSUE THREAD

**Issue by bhumeshvr7github** [sephiroth74/Material-BottomNavigation#84]
when i add more then five item, then app are force closing with error "java.lang.IllegalArgumentException: BottomNavigation expects 3 to 5 items. 6 found". how to solve this?

**Comment by sephiroth74** [comment]
As it's stated in the material specs (https://material.io/develop/android/components/bottom-navigation-view/) the bottom navigation component shouldn't have more than 5 items
